### ISSUE TITLE
PledgesController

### ISSUE THREAD

**Issue by kylekthompson** [emilyengle/hackathon-portal#20]
This will most likely be nested something like this: `/sponsors/sponsor1/pledges/new`

Only admins can create/view these.

Needs the following:
`index`, `new`, `create`, `edit`, `update`, `destroy`

requires authentication

**Comment by unkrich** [comment]
Again, shouldn't this be viewable by the sponsor in their portal?

**Comment by kylekthompson** [comment]
I don't think so. The pledge information is added by admins. This is purely internal tracking

**Comment by unkrich** [comment]
Okay .. I guess I was assuming we were showing that information back to the sponsors to make sure it was recorded correctly or if they were going to choose to update it i.e. adding hardware or something. I suppose either works.

**Comment by kylekthompson** [comment]
I feel like sponsors could be malicious about that and change their levels, etc.
