### ISSUE TITLE
ActiveRecord::RecordNotFound in StaticPagesController#index

### ISSUE THREAD

**Issue by unkrich** [emilyengle/hackathon-portal#28]
Session stores user id, if account is deleted or id changed, etc. then error occurs.

**Comment by unkrich** [comment]
This shouldn't really be a problem .. session should reset by the time (if) an account gets deleted..  no? @kylekthompson

**Comment by kylekthompson** [comment]
Ideally, they should even be deleting their own accounts.. or trying to log back in if they did delete it.

Quick solution is to just set the session to nil on `destroy` of User
