### ISSUE TITLE
Fix add pledges button

### ISSUE THREAD

**Issue by emilyengle** [emilyengle/hackathon-portal#32]
Fix add pledges button to display the add pledges fields (*cough* you had one job, @unkrich )

**Comment by unkrich** [comment]
That's one more job than you :O

**Comment by kylekthompson** [comment]
_ahem_ https://github.com/emilyengle/hackathon-portal/graphs/contributors

**Comment by unkrich** [comment]
> Perks of Kyle using your computer

**Comment by kylekthompson** [comment]
@unkrich that's so nice of you!

**Comment by unkrich** [comment]
@kylekthompson @emilyengle just saw that... regardless the problem seems to be a result of jQuery and turbolinks conflicts - didn't figure out resolution though
