### ISSUE TITLE
Pledge Model

### ISSUE THREAD

**Issue by kylekthompson** [emilyengle/hackathon-portal#4]
`level` enum (what are the sponsor pledge levels?)
`pledge_type` enum (`:monetary`, `:inkind`, `:both`)
`amount_pledged` integer
`amount_paid` integer
`inkind_pledged` integer
`inkind_received` integer
`sponsor_id`

`belongs_to :sponsor`

**Comment by unkrich** [comment]
This should be possible to make now that sponsor model is created 👍
